### Create a new company field
POST http://localhost:3000/company-field
Content-Type: application/json

{
    "name": "Education"
}


### Find a specific company field
GET http://localhost:3000/company-field/1


### Find a company field list
GET http://localhost:3000/company-field

### Create a company
POST http://localhost:3000/company
Content-Type: application/json

{
    "companyFieldId": 1,
    "description": "company desc",
    "websiteUrl": "website url",
    "logoImageUrl": "logo image url"
}